## Feature Engineering

Feature engineering is the process of **creating, transforming, or selecting features** from raw data to improve the performance of machine learning models.

It is one of the most important steps in data preprocessing.

Feature engineering mainly includes:

- Feature Transformation
- Feature Scaling
- Encoding Categorical Data

## Feature Transformation

 
Common transformations include:

- Log Transformation
- Square Root Transformation
- Polynomial Features
- Power Transformation

Purpose:
- Reduce skewness
- Improve model performance
- Make patterns easier for models to learn

---

## Feature Scaling

Feature scaling is the process of **bringing all numerical features to a similar scale** so that no feature dominates others.

Common methods:

### Min-Max Scaling

\[
X_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}}
\]

Range becomes **0 to 1**.

---

### Standardization (Z-score)

\[
Z = \frac{X - \mu}{\sigma}
\]

Where  
- \( \mu \) = mean  
- \( \sigma \) = standard deviation  

---

## What is Encoding?

Encoding is the process of converting **categorical (text) data into numerical format** so that machine learning algorithms can understand and process it.

Most machine learning models work only with numbers, so categorical values like "Male", "Female", or "Red", "Blue" must be converted into numbers.

---

## How Can We Encode Categorical Data?

There are several common techniques used to encode categorical variables:

### 1. Label Encoding
Each unique category is assigned a unique integer.

Example:

| Color | Encoded |
|------|------|
| Red | 0 |
| Blue | 1 |
| Green | 2 |

Best used when the categories have **ordinal meaning**.

---

### 2. One-Hot Encoding
Each category is converted into a **separate binary column**.

Example:

| Color | Red | Blue | Green |
|------|----|----|----|
| Red | 1 | 0 | 0 |
| Blue | 0 | 1 | 0 |
| Green | 0 | 0 | 1 |

This method avoids false ordering between categories.

---

### 3. Ordinal Encoding
Used when categorical data has a **natural order**.

Example:

| Size | Encoded |
|----|----|
| Small | 1 |
| Medium | 2 |
| Large | 3 |

---

## Encoding Categorical Data

Encoding categorical data is an important part of preprocessing where **text-based categories are converted into numeric values**.

Common encoding techniques:

- Label Encoding
- One-Hot Encoding
- Ordinal Encoding
- Target Encoding

These methods help machine learning models process categorical variables effectively.

## Encoding Categorical Data

Encoding is the process of converting **categorical (text) data into numerical form** so that machine learning algorithms can process it.

---

## 1. Label Encoding (Only Use For target varable Not For Feature)

Label Encoding converts each category into a **unique integer value**.

Example:

| Color | Encoded |
|------|------|
| Red | 0 |
| Blue | 1 |
| Green | 2 |

Characteristics:
- Simple and fast
- Assigns numbers to categories
- Can create **false ordering** between categories

Used when:
- Categories have **ordinal relationship**

Example:
Small < Medium < Large

---

## 2. One-Hot Encoding

One-Hot Encoding converts each category into **separate binary columns**.

Example:

| Color | Red | Blue | Green |
|------|----|----|----|
| Red | 1 | 0 | 0 |
| Blue | 0 | 1 | 0 |
| Green | 0 | 0 | 1 |

Characteristics:
- No ordinal relationship between categories
- Prevents misleading order
- Increases number of columns

Used when:
- Categories have **no natural order**

Example:
City names, product types.

---

## 3. Ordinal Encoding

Ordinal Encoding assigns **ordered numeric values** to categories that have a **natural ranking**.

Example:

| Education | Encoded |
|------|------|
| High School | 1 |
| Bachelor | 2 |
| Master | 3 |
| PhD | 4 |

Characteristics:
- Maintains order between categories
- Useful when ranking exists

Used when:
- Data has **clear hierarchy or ranking**

Example:
Low < Medium < High

---

## 4. Target Encoding

Target Encoding replaces a category with the **mean value of the target variable for that category**.

Example:

| City | Average House Price |
|----|----|
| Delhi | 500000 |
| Mumbai | 700000 |
| Patna | 300000 |

Characteristics:
- Uses information from the target variable
- Works well with **high-cardinality categorical data**

Risk:
- Can cause **data leakage** if not applied carefully.

---

## Summary

| Encoding Method | Best Use Case |
|------|------|
| Label Encoding | Ordered categories |
| One-Hot Encoding | Unordered categories |
| Ordinal Encoding | Ranked categories |
| Target Encoding | High-cardinality categories |

In [121]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Blue", "Red"]
})

le = LabelEncoder()

data["Color_encoded"] = le.fit_transform(data["Color"])

print(data)

   Color  Color_encoded
0    Red              2
1   Blue              0
2  Green              1
3   Blue              0
4    Red              2

In [123]:
import pandas as pd

data = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Blue", "Red"]
})

encoded = pd.get_dummies(data, columns=["Color"])

print(encoded.astype(int))

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           1            0          0
2           0            1          0
3           1            0          0
4           0            0          1

In [125]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

data = pd.DataFrame({
    "Size": ["Small", "Medium", "Large", "Medium", "Small"]
})

oe = OrdinalEncoder(categories=[["Small","Medium","Large"]])

data["Size_encoded"] = oe.fit_transform(data[["Size"]])

print(data)

     Size  Size_encoded
0   Small           0.0
1  Medium           1.0
2   Large           2.0
3  Medium           1.0
4   Small           0.0

In [127]:
import pandas as pd

data = pd.DataFrame({
    "City": ["Delhi","Mumbai","Delhi","Patna","Mumbai"],
    "Price": [500000,700000,550000,300000,720000]
})

target_mean = data.groupby("City")["Price"].mean()

data["City_encoded"] = data["City"].map(target_mean)

print(data)

     City   Price  City_encoded
0   Delhi  500000      525000.0
1  Mumbai  700000      710000.0
2   Delhi  550000      525000.0
3   Patna  300000      300000.0
4  Mumbai  720000      710000.0

In [129]:
df = pd.read_csv("customer.csv")

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [133]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [135]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [137]:


oe = OrdinalEncoder(categories = [['School', 'UG', 'PG']])

df["education_enc"] = oe.fit_transform(df[["education"]])

In [139]:
df.head()

   age  gender   review education purchased  education_enc
0   30  Female  Average    School        No            0.0
1   68  Female     Poor        UG        No            1.0
2   70  Female     Good        PG        No            2.0
3   72  Female     Good        PG        No            2.0
4   16  Female  Average        UG        No            1.0

In [141]:
df['purches_encoded'] = LabelEncoder().fit_transform(df['purchased'])

In [143]:
df.head()

   age  gender   review education purchased  education_enc  purches_encoded
0   30  Female  Average    School        No            0.0                0
1   68  Female     Poor        UG        No            1.0                0
2   70  Female     Good        PG        No            2.0                0
3   72  Female     Good        PG        No            2.0                0
4   16  Female  Average        UG        No            1.0                0

In [145]:
df["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [147]:
df["gender_encoded"] = LabelEncoder().fit_transform(df["gender"])

In [149]:
df.head()

,age,gender,review,education,purchased,education_enc,purches_encoded,gender_encoded
0,30,Female,Average,School,No,0.0,0,0
1,68,Female,Poor,UG,No,1.0,0,0
2,70,Female,Good,PG,No,2.0,0,0
3,72,Female,Good,PG,No,2.0,0,0
4,16,Female,Average,UG,No,1.0,0,0