In [48]:
import numpy as np
import pandas as pd

In [50]:
df = pd.read_csv("cars.csv")

In [52]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

df["brand"].value_counts()

In [13]:
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# 1. One Hot Encoding using Pandas

In [15]:
pd.get_dummies(df,columns=["fuel","owner"])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# 2. K-1 One hot Encoding

For Maintaing Multi Colinearity

In [18]:
pd.get_dummies(df,columns=["fuel","owner"],drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3 . One hot Encoding Using Sciket learn
- In data analysis we can use pandas but during making Ml project We can't
- Beacuse pandas don't remember In position Place all values

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =  train_test_split(df.iloc[:,0:4],
                                                  df.iloc[:,-1],test_size=0.2,random_state=42)

In [56]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [58]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [60]:
X_test.head()

       brand  km_driven    fuel         owner
1971   Honda     110000  Petrol   Third Owner
4664    Tata     291977  Diesel   First Owner
5448  Maruti      70000  Diesel   First Owner
3333   Honda     120000  Petrol  Second Owner
2316  Maruti      69000  Diesel  Second Owner

In [62]:
from sklearn.preprocessing import OneHotEncoder

In [77]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False)

In [79]:
x_train_new = ohe.fit_transform(X_train[['fuel','owner']])
x_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [87]:
x_train_new.shape

(6502, 7)

In [89]:
np.hstack((X_train[['brand','km_driven']].values,x_train_new)).shape

(6502, 9)

# 4.One Hot Encoding With Top categories

In [92]:
count = df["brand"].value_counts()

In [94]:
df["brand"].nunique()
threshold = 100

In [96]:
repl = count[count<= threshold].index

In [98]:
pd.get_dummies(df["brand"].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3563,False,False,False,False,True,False,False,False,False,False,False,False,False
6444,False,False,False,False,False,False,False,False,False,True,False,False,False
2327,False,False,False,False,False,False,True,False,False,False,False,False,False
1015,False,False,False,False,False,False,False,False,False,False,False,False,True
7918,False,False,True,False,False,False,False,False,False,False,False,False,False